### get home page
GET http://localhost:8080/
Authorization: Basic jayde:password

### getting a token
POST http://10.0.0.86:8080/token
Authorization: Basic chicken:cat

### get all users
GET  http://10.0.0.86:8080/users
Authorization: Basic chicken:cat

### Inserting a user into the database
POST http://10.0.0.86:8080/save
Content-Type: application/json

{
    "username" : "chicken",
    "password" : "cat"
}

### login
POST http://localhost:8080/login
Content-Type: application/json

{
    "username" : "chicken",
    "password" : "cat"
}

###delete a user
DELETE http://localhost:8080/delete/3

### updating a user
PUT http://localhost:8080/update/4
Content-Type: application/json

{
    "username" : "apples"
}