CREATE TABLE IF NOT EXISTS USERS (
    id INTEGER AUTO_INCREMENT,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    primary key(id)
);

CREATE TABLE IF NOT EXISTS FAVOURITES (
   userId INTEGER NOT NULL,
   recipeId INTEGER NOT NULL,
   PRIMARY KEY(userId, recipeId),
   FOREIGN KEY(userId) REFERENCES USERS(id) ON DELETE CASCADE
);